// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnSqiI5aws-b2MjmNU4a-e7bHh06CdQs',
    appId: '1:7062220856:web:a9372d2d91c10fb56136cd',
    messagingSenderId: '7062220856',
    projectId: 'canteen-app-5b5f9',
    authDomain: 'canteen-app-5b5f9.firebaseapp.com',
    storageBucket: 'canteen-app-5b5f9.firebasestorage.app',
    measurementId: 'G-BY83V70M1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrJX8fhgf-J5DmeEUENW-BJ-k4fX0cOw',
    appId: '1:7062220856:android:24ae906212a6ada36136cd',
    messagingSenderId: '7062220856',
    projectId: 'canteen-app-5b5f9',
    storageBucket: 'canteen-app-5b5f9.firebasestorage.app',
  );

}